### PR TITLE
Add basic_auth env variable to faas-containerd.service

### LINKED ISSUE #11: [Feature] Enable basic-auth for faasd-containerd in faasd install
## Expected Behaviour

Enable basic-auth in faasd install by updating faas-containerd's unit file to set the basic_auth=true env-var.

## Current Behaviour

Whilst faas-containerd now supports basic auth, it's disabled by default leaving it vulnerable, even if faasd and the gateway have it enabled.

## Possible Solution

Edit https://github.com/alexellis/faasd/blob/master/hack/faas-containerd.service

## Steps to Reproduce (for bugs)

1. Deploy via current faasd release
2. See that `curl -i host:8080/system/functions` has auth - status code 401
3. See that `curl -i host:8081/system/functions` has no auth - status code 200

To test the fix, carry out step 1 with your new binary and new systemd unit file in place in your GOPATH. i.e. `./faasd install`

Then repeat step 2 and step 3 making sure that both have auth enabled now, they should give status code 401.

### PR DESCRIPTION
**Pull request by markopolo123**
## Description
Edited the systemd service file to include an environment variable.

## Motivation and Context
Enables basic auth for faasd
Fixes #11 
- [x] I have raised an issue to propose this change **this is required**

## How Has This Been Tested?
Manually on a Pi4b
[asciinema recording of auth enabled](https://asciinema.org/a/IOa9CzpbaTDrcpXILp5i0P5uR)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by alexellis** [comment]
> How Has This Been Tested?

Sorry but you can't leave this blank. Please can you give console output of how you've tested this?

**Comment by alexellis** [comment]
Please go back to issue #11 and the README for further information.

**Comment by markopolo123** [comment]
Updated description with a screenshot of `sudo journalctl -u faasd`

**Comment by alexellis** [comment]
The screenshot does not show any evidence of testing, yesterday I added detail instructions for you on the original issue. Please go back and work through it then paste the output here.

**Comment by markopolo123** [comment]
[asciinema recording showing basic-auth-plugin enabled](https://asciinema.org/a/IOa9CzpbaTDrcpXILp5i0P5uR)

**Comment by alexellis** [comment]
I think I might have miscommunicated, I hope you don't mind as this is also your first contribution.

This is what we have on the Issue:

Screenshot 2020-01-05 at 08 29 17

I was just looking for you to provide the before/after curl statements and results.

The basic-auth-plugin is already loaded from a prior PR, we need to see that the `curl` statement to the provider is protected, in the scenario where the service is removed / disabled, then added by the faasd version in this patch.

The ascii cinema is fine, but you don't have to as much effort in future.

**Comment by alexellis** [comment]
It looks like the e2e tests are failing after the merge https://travis-ci.com/alexellis/faasd/builds/143133347

I've had a look into it, but haven't figured it out yet.

**Comment by alexellis** [comment]
It looks like you may have had something out of date, or didn't do a clean test since CI got an error about looking for secrets in `/var/run/secrets/`. I've had to do some extra work to get around this in the linked PR. Feel free to take a look.

**Pull request merged**
