### PR TITLE
Add multipass helpers, make helpers

### PR DESCRIPTION
**Pull request by gabeduke**
## Description
This adds the avahi-daemon for easy discoverability, and a helper script
to easily standup/teardown a multipass instace

I formatted the makefile with doc headings and groups. This is just a
suggestion, I'm happy to revert back to the undocumented style.

_Note_: The helper script replaces the `ssh-rsa` line in the
cloud-config.txt with the current users public key. We can create a
temporary file so that there is not a risk of commiting individual's
keys.

## Motivation and Context
As a developer I want to easily stand up and tear down the environment with a single command.

## How Has This Been Tested?
Tested on Ubuntu linux

## Types of changes
developer tooling

## Checklist:

Commits:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] My commit message has a body and describe how this was tested and why it is required.
- [x] I have signed-off my commits with `git commit -s` for the Developer Certificate of Origin (DCO)

Code:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.

Docs:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gabeduke** [comment]
I've realized that adding `avahi-daemon` won't actually resolve in most cases because FAAS-CLI is built with `CGO_ENABLED=0`. The only reason it was resolving for me is because I am using a custom built version of the CLI with `cgo` enabled. If there is strong opposition to enabling `cgo` then I would just remove the avahi-daemon pkg.

**Comment by gabeduke** [comment]
steps to validate:

1. `make multipass-run` (type yes when the prompt shows up to add pub key)
1. `make ssh` will rsync the repository to the appropriate place inside the multipass VM's GOPATH then ssh into the directory
1. `make dev` will rsync the repository into the multipass VM, build the go package and switch the new binary out with the running systemd service

**Comment by alexellis** [comment]
I see that you're having some issues using git and signing-off your commits. I do this with "git commit -s" and it works fairly well that way. 

If you have suggestions for enhancements please feel free to raise an issue to make sure we align and are happy to maintain those changes on an ongoing basis (see also contribution guide).

**Comment by gabeduke** [comment]
@alexellis The commits were all signed until I merged the secrets branch in. From there it got complicated. I thought I would just squash and make a single commit rather than fighting with git. Anyways the scope of the original PR grew as I added more functionality, I'll start a proposal to sort out any details before opening the PR back up.

**Comment by alexellis** [comment]
You might also want to work away in your own branch or another repo like faasd-my-playbook or similar? Interested to know how people will be deploying and updating their faasd VMs

**Comment by gabeduke** [comment]
I don't know yet either. The complicating factor is It is difficult to set up a development environment outside of a VM because my filesystem is ZFS (quirky with containerd). It is helpful to have the multipass environment to see what things _should_ look like, or maybe as a proxy target to run faasd on the host. 

Link: https://github.com/alexellis/faasd/issues/34

**Pull request closed without merging**
